baseURL = 'https://openaq-staging.org/'
languageCode = 'en-us'
title = 'OpenAQ'
theme = 'openaq'
copyright = "{year} OpenAQ. All rights reserved."

[permalinks]
  categories = "/use-cases/:slug/"
  tags = "/use-cases/:slug/"

[params]
  plausibleDomain = "openaq-staging.org"

[module]
  [[module.mounts]]
    source = "./node_modules/openaq-design-system/scss/"
    target = "assets/scss/openaq-design-system"
  [[module.mounts]]
    source = "content/uploads/"
    target = "assets/"
  [[module.imports]]
    path = "github.com/divinerites/plausible-hugo"